# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/app_send_sms.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("MainWindow{\n"
"background-color:lightblue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 40, 411, 471))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:yellow;\n"
"border:2px solid black;\n"
"border-radius:12px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 50, 321, 31))
        self.label.setStyleSheet("QLabel{\n"
"background-color:black;\n"
"font:Arial 20 bold;\n"
"color:white;\n"
"border-bottom:2px solid white;\n"
"border-radius:none;}")
        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLineEdit(self.frame)
        self.user_name.setGeometry(QtCore.QRect(50, 100, 321, 31))
        self.user_name.setStyleSheet("QLineEdit{\n"
"border-top:5px solid black;\n"
"}")
        self.user_name.setObjectName("user_name")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 321, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color:black;\n"
"font:Arial 20 bold;\n"
"color:white;\n"
"border-bottom:2px solid white;\n"
"border-radius:none;}")
        self.label_2.setObjectName("label_2")
        self.user_number = QtWidgets.QLineEdit(self.frame)
        self.user_number.setGeometry(QtCore.QRect(50, 199, 321, 31))
        self.user_number.setStyleSheet("QLineEdit{\n"
"border-top:5px solid black;\n"
"}\n"
"")
        self.user_number.setObjectName("user_number")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 249, 321, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"background-color:black;\n"
"font:Arial 20 bold;\n"
"color:white;\n"
"border-bottom:2px solid white;\n"
"border-radius:none;}\n"
"")
        self.label_3.setObjectName("label_3")
        self.user_speech = QtWidgets.QTextEdit(self.frame)
        self.user_speech.setGeometry(QtCore.QRect(50, 310, 321, 71))
        self.user_speech.setStyleSheet("QTextEdit{\n"
"background-color:lightgray;\n"
"border-radius:none;\n"
"border-bottom:2px solid white;\n"
"}")
        self.user_speech.setObjectName("user_speech")
        self.send_btn = QtWidgets.QPushButton(self.frame)
        self.send_btn.setGeometry(QtCore.QRect(50, 400, 321, 31))
        self.send_btn.setStyleSheet("QPushButton{\n"
"color:green;\n"
"font: Italic 20 bold;\n"
"background-color:white;\n"
"border-radius:13px;\n"
"border-bottom:2px solid black;}")
        self.send_btn.setObjectName("send_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">USER NAME</span></p></body></html>"))
        self.user_name.setPlaceholderText(_translate("MainWindow", "user name"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">NUMBER</span></p></body></html>"))
        self.user_number.setPlaceholderText(_translate("MainWindow", "number"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">SAY  ABOUT</span></p></body></html>"))
        self.user_speech.setPlaceholderText(_translate("MainWindow", "talk about any thing!"))
        self.send_btn.setText(_translate("MainWindow", "SEND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
